# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='naats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('vidPath', models.CharField(max_length=200)),
                ('imgPath', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='vidQualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vidTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='naats',
            name='quality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naats.vidQualities'),
        ),
        migrations.AddField(
            model_name='naats',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naats.vidTypes'),
        ),
    ]
